# Neural Networks Demystified - YouTube Series

Consider that we wish to model the score on a test, based on how many hours of sleep one receives.

Data set is the (hours of sleep, hours of study), mapped to the the output: a score on a test.

In [1]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image
from IPython.display import Latex

In [2]:
# X -> (hours of sleep, hours of study)
X = np.array(([3,5],[5,1],[10,2]), dtype=float)
y = np.array(([75],[82],[93]), dtype=float)

In [3]:
X

array([[  3.,   5.],
       [  5.,   1.],
       [ 10.,   2.]])

In [4]:
y

array([[ 75.],
       [ 82.],
       [ 93.]])

# Train a Model to Perform Supervised Regression
To train a model, we must define a training set, and a testing set. Regression implies predicting a continuous output, wheras classification implies predicting a categorical output.

I.e., what do we expect to get as a score, if we get 8 hours of sleep, and study for 3 hours?

First, data should be scaled (normalized) to fall within a range from 0 to 1 (what about continous data)?

$$X_{norm} = {{X}\over{max_{X}}}$$ 
$$y_{norm} = {{y}\over{100}}$$

In [29]:
X = X/np.amax(X,axis=0)
print(X)
y = y/100
print(y)

[[ 0.3  1. ]
 [ 0.5  0.2]
 [ 1.   0.4]]
[[ 0.0075]
 [ 0.0082]
 [ 0.0093]]


## Deep Network Example
A neural net can be represented by passing weighted sums of one layer of neruons to the next, and so on. In this configuration, we have 'deep learning'.
<img src="./img/neural_net_1.jpg">
Each layer of neurons is referred to as a 'hidden layer' since we don't actually observe the output of these layers, they are instead transformed back into 'X' space, as normal.


## Simple, Single Layer Network
In this case, we use one 'hidden layer' with three hidden units, which under the neuronal analogy are referred to as 'neurons'.

<img src="./img/neural_net_2.jpg">

Circles are neurons, lines are synapses. Neurons add output from synapses and apply an activation funciton. We use sigmoid activation function on this case.

Without training, our Neural_Network Object will simply give us garbage, because we've initialized the weights with random numbers. We could essentially try all combinations of nine weights to obtain the 'best fit' but of course, enter the curse of dimensionality. We quickly run out of computing power as we increase the dimensionality.




In [10]:
class Neural_Network(object):
    def __init__(self):
        # Hyperparameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
    
        # Weights
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
    
    # Activation function
    def sigmoid(self,z):
        # Apply sigmoid activation function
        return 1/(1+np.exp(-z))
    
    # Forward Propagation
    def forward(self,X):
        # Propagate inputs through network using matries
        self.z2 = np.dot(X,self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2,self.W2)
        yHat = self.sigmoid(self.z3)
        return yHat

In [27]:
# Handle instance
NN = Neural_Network()
yHat = NN.forward(X)

In [28]:
yHat

array([[ 0.45281219],
       [ 0.39943534],
       [ 0.4383842 ]])

In [ ]:
# Simple plot example
plot_domain = np.arange(-6,6,0.01) # np array from -6 to 6 in steps of 0.01
plt.plot(plot_domain, sigmoid(plot_domain), linewidth=2)
plt.grid(1)

# Numpy note - applies functions element-wise to containers as a convention - pretty neat!